### ISSUE TITLE
normalize input file

### ISSUE THREAD

**Issue by kaat0** [gwehrle/Overpass.jl#18]
Loading of a file exported from Overpass Turbo fails.

This is due to multiple new lines and comments:
```
// @name Drinking Water

/*
This is an example Overpass query.
source: https://overpass-turbo.eu
*/

[out:json];

node
  [amenity=drinking_water]
  ({{bbox}});
out;
```

The expected query from this file is:
`[out:json];node[amenity=drinking_water]({{bbox}});out;` without comments and new lines.

**Comment by gwehrle** [comment]
I used this exact query, put it into overpassturbo, exported it and called it with Overpass.query("query-raw.overpassql", bbox=(…)) and it works as expected. Can you provide the error message?

**Comment by gwehrle** [comment]
Overpass API should handle comments and line breaks.
These is the request form Overpass Turbo to Overpass API with your query:

`"//+@name+Drinking+Water\n\n/*\nThis+is+an+example+Overpass+query.\nsource:+https://overpass-turbo.eu\n*/\n\n[out:json];\n\nnode\n++[amenity=drinking_water]\n++(48.22518727942031,16.360584497451786,48.22625583460687,16.36472046375275);\nout;\n"`

Comments and line breaks are not removed.

**Comment by kaat0** [comment]
Sorry, I expected the query to work differently.

A function `normalize_query()` could shorten URLs for the API call.

```
function normalize_query(query::String)::String
    query = split(query, "\n")

    # helper
    deletion = Vector{Bool}(undef,length(query))
    fill!(deletion, false)
    is_comment = false

    for idx = eachindex(query)
        if is_comment # remove /* */ comments - part 2
            deletion[idx] = true
            contains(query[idx], "*/") ? is_comment = false : nothing
        else
            if startswith(query[idx], "/*")  # remove /* */ comments - part 1
                deletion[idx] = true
                is_comment = true
            else
                startswith(query[idx], "//") ? deletion[idx] = true : nothing # remove // comments
                isempty(query[idx]) ? deletion[idx] = true : nothing # remove empty lines
                query[idx] = lstrip(query[idx]) # remove leading white spaces
                query[idx] = rstrip(query[idx]) # remove trailing white spaces
            end
        end
    end

    deleteat!(query,deletion)
    query = join(query)

    @debug "query after normalization" query
    return query
end
```

**Comment by gwehrle** [comment]
I'm always very cautious with optimizing or editing queries, because it can lead to unwandted side effects. Overpass.jl uses POST to send the query to the Overpass API.  Thus the query is not appended to the url, so query size should not be a problem.

Parsing queries can be very tricky. For example your current implementation would **delete** the whole line: 
`nwr[amenity] \* comment *\`
but the corecct way would be to strip it to  `nwr[amenity]`.

As there is no bug or problem I'll close this issue, until noralization is really needed.
